spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:ticket_market}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:loxy1517}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: /db/changelog/changes/changelog-master.xml
server:
  port: 8080
